using System;
using System.Collections.Generic;

namespace AFBA.EPP.Models
{
    public partial class EppPartnersDataErr
    {
        public EppPartnersDataErr()
        {
            EppErrorDtl = new HashSet<EppErrorDtl>();
        }

        public long RcrdId { get; set; }
        public string FileNm { get; set; }
        public string PolcyNbr { get; set; }
        public string PrductCd { get; set; }
        public string UsrTkn { get; set; }
        public string GrpNmbr { get; set; }
        public string GrpNm { get; set; }
        public string GrpSitusState { get; set; }
        public string IssueDt { get; set; }
        public string BillingCtgry { get; set; }
        public string EmpQualityOfLife { get; set; }
        public string EmpWaiverOfPrem { get; set; }
        public string Basplan { get; set; }
        public string Opt { get; set; }
        public string EnrlActn { get; set; }
        public string EnrlTyp { get; set; }
        public string EffctvDt { get; set; }
        public string ApplicationDt { get; set; }
        public string TimeStamp { get; set; }
        public string SigndAtCity { get; set; }
        public string SigndAtState { get; set; }
        public string PaymentMode { get; set; }
        public string AgntCd1 { get; set; }
        public string Agntsub1 { get; set; }
        public string AgntNm { get; set; }
        public string AgntCommSplit1 { get; set; }
        public string AgntSigTxt1 { get; set; }
        public string AgntCd2 { get; set; }
        public string Agntsub2 { get; set; }
        public string AgntCommSplit2 { get; set; }
        public string AgntSigTxt2 { get; set; }
        public string AgntCd3 { get; set; }
        public string Agntsub3 { get; set; }
        public string AgntCommSplit3 { get; set; }
        public string AgntSigTxt3 { get; set; }
        public string AgntCd4 { get; set; }
        public string Agntsub4 { get; set; }
        public string AgntCommSplit4 { get; set; }
        public string AgntSigTxt4 { get; set; }
        public string ExistingIns { get; set; }
        public string ReplacingIns { get; set; }
        public string RateLvl { get; set; }
        public string OwnersLname { get; set; }
        public string OwnersFname { get; set; }
        public string OwnersMidInit { get; set; }
        public string OwnersDob { get; set; }
        public string OwnersSsn { get; set; }
        public string OwnersSex { get; set; }
        public string OwnerSmkrNoSmkr { get; set; }
        public string OwnerHght { get; set; }
        public string OwnerWght { get; set; }
        public string OwnerSal { get; set; }
        public string OwnersPhn { get; set; }
        public string OwnersAddrLn1 { get; set; }
        public string OwnersAddrLn2 { get; set; }
        public string OwnersAddrCity { get; set; }
        public string OwnersAddrState { get; set; }
        public string OwnersAddrZip { get; set; }
        public string CvrdPrsn { get; set; }
        public string EmpSigDt { get; set; }
        public string EmpSigTxt { get; set; }
        public string EmailAddr { get; set; }
        public string AccidntCat { get; set; }
        public string HspitalIndmnty { get; set; }
        public string EmpId { get; set; }
        public string EmpPlanCd { get; set; }
        public string EmpCovTyp { get; set; }
        public string EmpFname { get; set; }
        public string EmpMidInit { get; set; }
        public string EmpLname { get; set; }
        public string EmpHeight { get; set; }
        public string EmpAddrLn1 { get; set; }
        public string EmpAddrLn2 { get; set; }
        public string EmpAddCity { get; set; }
        public string EmpAddrState { get; set; }
        public string EmpAddrZip { get; set; }
        public string EmpDob { get; set; }
        public string EmpGndr { get; set; }
        public string EmpWeight { get; set; }
        public string EmpHireDt { get; set; }
        public string ActivlyAtWrk { get; set; }
        public string EmpHandicppd { get; set; }
        public string EmpSsn { get; set; }
        public string EmpPrimBeneNm01 { get; set; }
        public string EmpPrimBenePercent01 { get; set; }
        public string EmpPrimBeneSsn01 { get; set; }
        public string EmpPrimBeneRel01 { get; set; }
        public string EmpPrimBeneAddrLn101 { get; set; }
        public string EmpPrimBeneAddrLn201 { get; set; }
        public string EmpPrimBeneAddrCty01 { get; set; }
        public string EmpPrimBeneAddrState01 { get; set; }
        public string EmpPrimBeneAddrZip01 { get; set; }
        public string EmpPrimBeneNm02 { get; set; }
        public string EmpPrimBenePercent02 { get; set; }
        public string EmpPrimBeneSsn02 { get; set; }
        public string EmpPrimBeneRel02 { get; set; }
        public string EmpPrimBeneAddrLn102 { get; set; }
        public string EmpPrimBeneAddrLn202 { get; set; }
        public string EmpPrimBeneAddrCity02 { get; set; }
        public string EmpPrimBeneAddrState02 { get; set; }
        public string EmpPrimBeneAddrZip02 { get; set; }
        public string EmpPrimBeneNm03 { get; set; }
        public string EmpPrimBenePercent03 { get; set; }
        public string EmpPrimBeneSsn03 { get; set; }
        public string EmpPrimBeneRel03 { get; set; }
        public string EmpPrimBeneAddrLn103 { get; set; }
        public string EmpPrimBeneAddrLn203 { get; set; }
        public string EmpPrimBeneAddrCity03 { get; set; }
        public string EmpPrimBeneAddrState03 { get; set; }
        public string EmpPrimBeneAddrZip03 { get; set; }
        public string EmpPrimBeneNm04 { get; set; }
        public string EmpPrimBenePercent04 { get; set; }
        public string EmpPrimBeneSsn04 { get; set; }
        public string EmpPrimBeneRel04 { get; set; }
        public string EmpPrimBeneAddrLn104 { get; set; }
        public string EmpPrimBeneAddrLn204 { get; set; }
        public string EmpPrimBeneAddrCity04 { get; set; }
        public string EmpPrimBeneAddrState04 { get; set; }
        public string EmpPrimBeneAddrZip04 { get; set; }
        public string EmpContBeneNm { get; set; }
        public string EmpContBenePercent { get; set; }
        public string EmpContBeneSsn { get; set; }
        public string EmpContBeneRel { get; set; }
        public string EmpContBeneAddrLn1 { get; set; }
        public string EmpContBeneAddrLn2 { get; set; }
        public string EmpContBeneAddrCty { get; set; }
        public string EmpContBeneAddrState { get; set; }
        public string EmpContBeneAddrZp { get; set; }
        public string EmpOccClass { get; set; }
        public string EmpCovAmnt { get; set; }
        public string EmpPrem { get; set; }
        public string EmpFaceAmtMonBnft { get; set; }
        public string EmpPlanFrmCd { get; set; }
        public string EmpPlanOptn { get; set; }
        public string EmpAdBnft { get; set; }
        public string EmpQstn1 { get; set; }
        public string EmpQstn1a { get; set; }
        public string EmpQstn1b { get; set; }
        public string EmpQstn2 { get; set; }
        public string EmpQstn3 { get; set; }
        public string EmpQstn3a { get; set; }
        public string EmpQstn3b { get; set; }
        public string EmpQstn3c { get; set; }
        public string EmpQstn3d { get; set; }
        public string EmpQstn3e { get; set; }
        public string EmpQstn4 { get; set; }
        public string EmpQstn5 { get; set; }
        public string EmpQstn6 { get; set; }
        public string EmpQstn7 { get; set; }
        public string EmpQstn8 { get; set; }
        public string EmpQstn9 { get; set; }
        public string EmpQstn10 { get; set; }
        public string SpFname { get; set; }
        public string SpMidInit { get; set; }
        public string SpLname { get; set; }
        public string SpHandicppd { get; set; }
        public string SpAddrLn1 { get; set; }
        public string SpAddrLn2 { get; set; }
        public string SpAddrCity { get; set; }
        public string SpAddrState { get; set; }
        public string SpAddrZip { get; set; }
        public string SpDob { get; set; }
        public string SpGndr { get; set; }
        public string SpSmkrNoSmkr { get; set; }
        public string SpHght { get; set; }
        public string SpWght { get; set; }
        public string SpSsn { get; set; }
        public string SpPrimBeneNm { get; set; }
        public string SpPrimBeneDob { get; set; }
        public string SpPrimBenePercent { get; set; }
        public string SpPrimBeneSsn { get; set; }
        public string SpPrimBeneRel { get; set; }
        public string SpPrimBeneAddrLn1 { get; set; }
        public string SpPrimBeneAddrLn2 { get; set; }
        public string SpPrimBeneAddrCty { get; set; }
        public string SpPrimBeneAddrState { get; set; }
        public string SpPrimBeneAddrZip { get; set; }
        public string SpOccClass { get; set; }
        public string SpCovAmnt { get; set; }
        public string SpPrem { get; set; }
        public string SpPlanCd { get; set; }
        public string SpCovTyp { get; set; }
        public string SpCovTypDesc { get; set; }
        public string SpFaceAmtMonBnft { get; set; }
        public string SpPlanFrmCd { get; set; }
        public string SpPlanOptn { get; set; }
        public string SpAdBnft { get; set; }
        public string SpQualityOfLife { get; set; }
        public string SpWaiverOfPrem { get; set; }
        public string SpQstn1 { get; set; }
        public string SpQstn1a { get; set; }
        public string SpQstn1b { get; set; }
        public string SpQstn2 { get; set; }
        public string SpQstn3 { get; set; }
        public string SpQstn3a { get; set; }
        public string SpQstn3b { get; set; }
        public string SpQstn3c { get; set; }
        public string SpQstn3d { get; set; }
        public string SpQstn3e { get; set; }
        public string SpQstn4 { get; set; }
        public string SpQstn5 { get; set; }
        public string SpQstn6 { get; set; }
        public string SpQstn7 { get; set; }
        public string SpQstn8 { get; set; }
        public string SpQstn9 { get; set; }
        public string SpQstn10 { get; set; }
        public string ChCovAmnt { get; set; }
        public string ChPlanCd { get; set; }
        public string ChCovTyp { get; set; }
        public string ChFname01 { get; set; }
        public string ChMidInit01 { get; set; }
        public string ChLname01 { get; set; }
        public string ChHandicppd01 { get; set; }
        public string ChDob01 { get; set; }
        public string ChGndr01 { get; set; }
        public string ChHght01 { get; set; }
        public string ChWght01 { get; set; }
        public string ChSsn01 { get; set; }
        public string ChCovTyp01 { get; set; }
        public string ChPrem01 { get; set; }
        public string ChPrimBeneNm01 { get; set; }
        public string ChPrimBenePercent01 { get; set; }
        public string ChPrimBeneSsn01 { get; set; }
        public string ChPrimBeneRel01 { get; set; }
        public string ChPrimBeneAddrLn1 { get; set; }
        public string ChPrimBeneAddrLn2 { get; set; }
        public string ChPrimBeneAddrCty { get; set; }
        public string ChPrimBeneAddrState { get; set; }
        public string ChPrimBeneAddrZip { get; set; }
        public string ChFaceAmtMonBnft01 { get; set; }
        public string ChOccClass01 { get; set; }
        public string ChPlanfrmcd01 { get; set; }
        public string ChPlanoptn01 { get; set; }
        public string ChAdBnft01 { get; set; }
        public string ChQstn101 { get; set; }
        public string ChQstn1a01 { get; set; }
        public string ChQstn1b01 { get; set; }
        public string ChQstn201 { get; set; }
        public string ChQstn301 { get; set; }
        public string ChQstn3a01 { get; set; }
        public string ChQstn3b01 { get; set; }
        public string ChQstn3c01 { get; set; }
        public string ChQstn3d01 { get; set; }
        public string ChQstn3e01 { get; set; }
        public string ChQstn401 { get; set; }
        public string ChQstn501 { get; set; }
        public string ChQstn601 { get; set; }
        public string ChQstn701 { get; set; }
        public string ChQstn801 { get; set; }
        public string ChQstn901 { get; set; }
        public string ChQstn1001 { get; set; }
        public string ChFname02 { get; set; }
        public string ChMidInit02 { get; set; }
        public string ChLname02 { get; set; }
        public string ChHandicppd02 { get; set; }
        public string ChDob02 { get; set; }
        public string ChGndr02 { get; set; }
        public string ChHght02 { get; set; }
        public string ChWght02 { get; set; }
        public string ChSsn02 { get; set; }
        public string ChCovTyp02 { get; set; }
        public string ChPrem02 { get; set; }
        public string ChPrimBeneNm02 { get; set; }
        public string ChPrimBeneSsn02 { get; set; }
        public string ChPrimBeneRel02 { get; set; }
        public string ChFaceAmtMonBnft02 { get; set; }
        public string ChOccClass02 { get; set; }
        public string ChPlanfrmcd02 { get; set; }
        public string ChPlanoptn02 { get; set; }
        public string ChAdBnft02 { get; set; }
        public string ChQstn102 { get; set; }
        public string ChQstn1a02 { get; set; }
        public string ChQstn1b02 { get; set; }
        public string ChQstn202 { get; set; }
        public string ChQstn302 { get; set; }
        public string ChQstn3a02 { get; set; }
        public string ChQstn3b02 { get; set; }
        public string ChQstn3c02 { get; set; }
        public string ChQstn3d02 { get; set; }
        public string ChQstn3e02 { get; set; }
        public string ChQstn402 { get; set; }
        public string ChQstn502 { get; set; }
        public string ChQstn602 { get; set; }
        public string ChQstn702 { get; set; }
        public string ChQstn802 { get; set; }
        public string ChQstn902 { get; set; }
        public string ChQstn1002 { get; set; }
        public string ChFname03 { get; set; }
        public string ChMidInit03 { get; set; }
        public string ChLname03 { get; set; }
        public string ChHandcppd03 { get; set; }
        public string ChDob03 { get; set; }
        public string ChGndr03 { get; set; }
        public string ChHght03 { get; set; }
        public string ChWght03 { get; set; }
        public string ChSsn03 { get; set; }
        public string ChCovTyp03 { get; set; }
        public string ChPrem03 { get; set; }
        public string ChPrimBeneNm03 { get; set; }
        public string ChPrimBeneSsn03 { get; set; }
        public string ChPrimBeneRel03 { get; set; }
        public string ChFaceAmtMonBnft03 { get; set; }
        public string ChOccClass03 { get; set; }
        public string ChPlanfrmcd03 { get; set; }
        public string ChPlanoptn03 { get; set; }
        public string ChAdBnft03 { get; set; }
        public string ChQstn103 { get; set; }
        public string ChQstn1a03 { get; set; }
        public string ChQstn1b03 { get; set; }
        public string ChQstn203 { get; set; }
        public string ChQstn303 { get; set; }
        public string ChQstn3a03 { get; set; }
        public string ChQstn3b03 { get; set; }
        public string ChQstn3c03 { get; set; }
        public string ChQstn3d03 { get; set; }
        public string ChQstn3e03 { get; set; }
        public string ChQstn403 { get; set; }
        public string ChQstn503 { get; set; }
        public string ChQstn603 { get; set; }
        public string ChQstn703 { get; set; }
        public string ChQstn803 { get; set; }
        public string ChQstn903 { get; set; }
        public string ChQstn1003 { get; set; }
        public string ChFname04 { get; set; }
        public string ChMidInit04 { get; set; }
        public string ChLname04 { get; set; }
        public string ChHandcppd04 { get; set; }
        public string ChDob04 { get; set; }
        public string ChGndr04 { get; set; }
        public string ChHght04 { get; set; }
        public string ChWght04 { get; set; }
        public string ChSsn04 { get; set; }
        public string ChCovTyp04 { get; set; }
        public string ChPrem04 { get; set; }
        public string ChPrimBeneNm04 { get; set; }
        public string ChPrimBeneSsn04 { get; set; }
        public string ChPrimBeneRel04 { get; set; }
        public string ChFaceAmtMonBnft04 { get; set; }
        public string ChOccClass04 { get; set; }
        public string ChAdBnft04 { get; set; }
        public string ChQstn104 { get; set; }
        public string ChQstn1a04 { get; set; }
        public string ChQstn1b04 { get; set; }
        public string ChQstn204 { get; set; }
        public string ChQstn304 { get; set; }
        public string ChQstn3a04 { get; set; }
        public string ChQstn3b04 { get; set; }
        public string ChQstn3c04 { get; set; }
        public string ChQstn3d04 { get; set; }
        public string ChQstn3e04 { get; set; }
        public string ChQstn404 { get; set; }
        public string ChQstn504 { get; set; }
        public string ChQstn604 { get; set; }
        public string ChQstn704 { get; set; }
        public string ChQstn804 { get; set; }
        public string ChQstn904 { get; set; }
        public string ChQstn1004 { get; set; }
        public string ChFname05 { get; set; }
        public string ChMidInit05 { get; set; }
        public string ChLstNam05 { get; set; }
        public string ChHandcappd05 { get; set; }
        public string ChDob05 { get; set; }
        public string ChGndr05 { get; set; }
        public string ChHght05 { get; set; }
        public string ChWght05 { get; set; }
        public string ChSsn05 { get; set; }
        public string ChCovTyp05 { get; set; }
        public string ChPrem05 { get; set; }
        public string ChPrimBeneNm05 { get; set; }
        public string ChPrimBeneSsn05 { get; set; }
        public string ChPrimBeneRel05 { get; set; }
        public string ChFaceAmtMonBnft05 { get; set; }
        public string ChOccClass05 { get; set; }
        public string ChAdBnft05 { get; set; }
        public string ChQstn105 { get; set; }
        public string ChQstn1a05 { get; set; }
        public string ChQstn1b05 { get; set; }
        public string ChQstn205 { get; set; }
        public string ChQstn305 { get; set; }
        public string ChQstn3a05 { get; set; }
        public string ChQstn3b05 { get; set; }
        public string ChQstn3c05 { get; set; }
        public string ChQstn3d05 { get; set; }
        public string ChQstn3e05 { get; set; }
        public string ChQstn405 { get; set; }
        public string ChQstn505 { get; set; }
        public string ChQstn605 { get; set; }
        public string ChQstn705 { get; set; }
        public string ChQstn805 { get; set; }
        public string ChQstn905 { get; set; }
        public string ChQstn1005 { get; set; }
        public string ChFname06 { get; set; }
        public string ChMidInit06 { get; set; }
        public string ChLname06 { get; set; }
        public string ChHandcppd06 { get; set; }
        public string ChDob06 { get; set; }
        public string ChGndr06 { get; set; }
        public string ChHght06 { get; set; }
        public string ChWght06 { get; set; }
        public string ChSsn06 { get; set; }
        public string ChCovTyp06 { get; set; }
        public string ChPrem06 { get; set; }
        public string ChPrimBeneNm06 { get; set; }
        public string ChPrimBeneSsn06 { get; set; }
        public string ChPrimBeneRel06 { get; set; }
        public string ChFaceAmtMonBnft06 { get; set; }
        public string ChOccClass06 { get; set; }
        public string ChAdBnft06 { get; set; }
        public string ChQstn106 { get; set; }
        public string ChQstn1a06 { get; set; }
        public string ChQstn1b06 { get; set; }
        public string ChQstn206 { get; set; }
        public string ChQstn306 { get; set; }
        public string ChQstn3a06 { get; set; }
        public string ChQstn3b06 { get; set; }
        public string ChQstn3c06 { get; set; }
        public string ChQstn3d06 { get; set; }
        public string ChQstn3e06 { get; set; }
        public string ChQstn406 { get; set; }
        public string ChQstn506 { get; set; }
        public string ChQstn606 { get; set; }
        public string ChQstn706 { get; set; }
        public string ChQstn806 { get; set; }
        public string ChQstn906 { get; set; }
        public string ChQstn1006 { get; set; }
        public string ChFname07 { get; set; }
        public string ChMidInit07 { get; set; }
        public string ChLname07 { get; set; }
        public string ChHandcappd07 { get; set; }
        public string ChDob07 { get; set; }
        public string ChGndr07 { get; set; }
        public string ChHght07 { get; set; }
        public string ChWght07 { get; set; }
        public string ChSsn07 { get; set; }
        public string ChCovTyp07 { get; set; }
        public string ChPrem07 { get; set; }
        public string ChPrimBeneNm07 { get; set; }
        public string ChPrimBeneSsn07 { get; set; }
        public string ChPrimBeneRel07 { get; set; }
        public string ChFaceAmtMonBnft07 { get; set; }
        public string ChOccClass07 { get; set; }
        public string ChAdBnft07 { get; set; }
        public string ChQstn107 { get; set; }
        public string ChQstn1a07 { get; set; }
        public string ChQstn1b07 { get; set; }
        public string ChQstn207 { get; set; }
        public string ChQstn307 { get; set; }
        public string ChQstn3a07 { get; set; }
        public string ChQstn3b07 { get; set; }
        public string ChQstn3c07 { get; set; }
        public string ChQstn3d07 { get; set; }
        public string ChQstn3e07 { get; set; }
        public string ChQstn407 { get; set; }
        public string ChQstn507 { get; set; }
        public string EmpPrimBeneNm { get; set; }
        public string EmpPrimBeneDob { get; set; }
        public string EmpPrimBeneRel { get; set; }
        public string EmpPrimBeneSsn { get; set; }
        public string EmpContBeneDob { get; set; }
        public string SpContBeneNm { get; set; }
        public string SpContBeneDob { get; set; }
        public string SpContBeneRel { get; set; }
        public string SpContBeneSsn { get; set; }
        public string EmpPrimBeneDob01 { get; set; }
        public string EmpContBeneNm01 { get; set; }
        public string EmpContBeneDob01 { get; set; }
        public string EmpContBeneRel01 { get; set; }
        public string EmpContBeneSsn01 { get; set; }
        public string EmpContBenePercent01 { get; set; }
        public string SpContBeneNm01 { get; set; }
        public string SpContBeneDob01 { get; set; }
        public string SpContBeneRel01 { get; set; }
        public string SpContBeneSsn01 { get; set; }
        public string SpContBenePercent01 { get; set; }
        public string EmpPrimBeneDob02 { get; set; }
        public string SpPrimBeneNm02 { get; set; }
        public string SpPrimBeneDob02 { get; set; }
        public string SpPrimBeneRel02 { get; set; }
        public string SpPrimBeneSsn02 { get; set; }
        public string SpPrimBenePercent02 { get; set; }
        public string EmpContBeneNm02 { get; set; }
        public string EmpContBeneDob02 { get; set; }
        public string EmpContBeneRel02 { get; set; }
        public string EmpContBeneSsn02 { get; set; }
        public string EmpContBenePercent02 { get; set; }
        public string SpContBeneNm02 { get; set; }
        public string SpContBeneDob02 { get; set; }
        public string SpContBeneRel02 { get; set; }
        public string SpContBeneSsn02 { get; set; }
        public string SpContBenePercent02 { get; set; }
        public string EmpPrimBeneDob03 { get; set; }
        public string SpPrimBeneNm03 { get; set; }
        public string SpPrimBeneDob03 { get; set; }
        public string SpPrimBeneRel03 { get; set; }
        public string SpPrimBeneSsn03 { get; set; }
        public string SpPrimBenePercent03 { get; set; }
        public string EmpContBeneNm03 { get; set; }
        public string EmpContBeneDob03 { get; set; }
        public string EmpContBeneRel03 { get; set; }
        public string EmpContBeneSsn03 { get; set; }
        public string EmpContBenePercent03 { get; set; }
        public string SpContBeneNm03 { get; set; }
        public string SpContBeneDob03 { get; set; }
        public string SpContBeneRel03 { get; set; }
        public string SpContBeneSsn03 { get; set; }
        public string SpContBenePercent03 { get; set; }
        public string EmpPrimBeneDob04 { get; set; }
        public string SpPrimBeneNm04 { get; set; }
        public string SpPrimBeneDob04 { get; set; }
        public string SpPrimBeneRel04 { get; set; }
        public string SpPrimBeneSsn04 { get; set; }
        public string SpPrimBenePercent04 { get; set; }
        public string EmpContBeneNm04 { get; set; }
        public string EmpContBeneDob04 { get; set; }
        public string EmpContBeneRel04 { get; set; }
        public string EmpContBeneSsn04 { get; set; }
        public string EmpContBenePercent04 { get; set; }
        public string SpContBeneNm04 { get; set; }
        public string SpContBeneDob04 { get; set; }
        public string SpContBeneRel04 { get; set; }
        public string SpContBeneSsn04 { get; set; }
        public string SpContBenePercent04 { get; set; }
        public string EmpPrimBeneNm05 { get; set; }
        public string EmpPrimBeneDob05 { get; set; }
        public string EmpPrimBeneRel05 { get; set; }
        public string EmpPrimBeneSsn05 { get; set; }
        public string EmpPrimBenePercent05 { get; set; }
        public string SpPrimBeneNm05 { get; set; }
        public string SpPrimBeneDob05 { get; set; }
        public string SpPrimBeneRel05 { get; set; }
        public string SpPrimBeneSsn05 { get; set; }
        public string SpPrimBenePercent05 { get; set; }
        public string EmpContBeneNm05 { get; set; }
        public string EmpContBeneDob05 { get; set; }
        public string EmpContBeneRel05 { get; set; }
        public string EmpContBeneSsn05 { get; set; }
        public string EmpContBenePercent05 { get; set; }
        public string SpContBeneNm05 { get; set; }
        public string SpContBeneDob05 { get; set; }
        public string SpContBeneRel05 { get; set; }
        public string SpContBeneSsn05 { get; set; }
        public string SpContBenePercent05 { get; set; }
        public string EmpPrimBeneNm06 { get; set; }
        public string EmpPrimBeneDob06 { get; set; }
        public string EmpPrimBeneRel06 { get; set; }
        public string EmpPrimBeneSsn06 { get; set; }
        public string EmpPrimBenePercent06 { get; set; }
        public string SpPrimBeneNm06 { get; set; }
        public string SpPrimBeneDob06 { get; set; }
        public string SpPrimBeneRel06 { get; set; }
        public string SpPrimBeneSsn06 { get; set; }
        public string SpPrimBenePercent06 { get; set; }
        public string EmpContBeneNm06 { get; set; }
        public string EmpContBeneDob06 { get; set; }
        public string EmpContBeneRel06 { get; set; }
        public string EmpContBeneSsn06 { get; set; }
        public string EmpContBenePercent06 { get; set; }
        public string SpContBeneNm06 { get; set; }
        public string SpContBeneDob06 { get; set; }
        public string SpContBeneRel06 { get; set; }
        public string SpContBeneSsn06 { get; set; }
        public string SpContBenePercent06 { get; set; }
        public string EmpPrimBeneNm07 { get; set; }
        public string EmpPrimBeneDob07 { get; set; }
        public string EmpPrimBeneRel07 { get; set; }
        public string EmpPrimBeneSsn07 { get; set; }
        public string EmpPrimBenePercent07 { get; set; }
        public string SpPrimBeneNm07 { get; set; }
        public string SpPrimBeneDob07 { get; set; }
        public string SpPrimBeneRel07 { get; set; }
        public string SpPrimBeneSsn07 { get; set; }
        public string SpPrimBenePercent07 { get; set; }
        public string EmpContBeneNm07 { get; set; }
        public string EmpContBeneDob07 { get; set; }
        public string EmpContBeneRel07 { get; set; }
        public string EmpContBeneSsn07 { get; set; }
        public string EmpContBenePercent07 { get; set; }
        public string SpContBeneNm07 { get; set; }
        public string SpContBeneDob07 { get; set; }
        public string SpContBeneRel07 { get; set; }
        public string SpContBeneSsn07 { get; set; }
        public string SpContBenePercent07 { get; set; }
        public string EmpPrimBeneNm08 { get; set; }
        public string EmpPrimBeneDob08 { get; set; }
        public string EmpPrimBeneRel08 { get; set; }
        public string EmpPrimBeneSsn08 { get; set; }
        public string EmpPrimBenePercent08 { get; set; }
        public string SpPrimBeneNm08 { get; set; }
        public string SpPrimBeneDob08 { get; set; }
        public string SpPrimBeneRel08 { get; set; }
        public string SpPrimBeneSsn08 { get; set; }
        public string SpPrimBenePercent08 { get; set; }
        public string EmpContBeneNm08 { get; set; }
        public string EmpContBeneDob08 { get; set; }
        public string EmpContBeneRel08 { get; set; }
        public string EmpContBeneSsn08 { get; set; }
        public string EmpContBenePercent08 { get; set; }
        public string SpContBeneNm08 { get; set; }
        public string SpContBeneDob08 { get; set; }
        public string SpContBeneRel08 { get; set; }
        public string SpContBeneSsn08 { get; set; }
        public string SpContBenePercent08 { get; set; }
        public string EmpPrimBeneNm09 { get; set; }
        public string EmpPrimBeneDob09 { get; set; }
        public string EmpPrimBeneRel09 { get; set; }
        public string EmpPrimBeneSsn09 { get; set; }
        public string EmpPrimBenePercent09 { get; set; }
        public string SpPrimBeneNm09 { get; set; }
        public string SpPrimBeneDob09 { get; set; }
        public string SpPrimBeneRel09 { get; set; }
        public string SpPrimBeneSsn09 { get; set; }
        public string SpPrimBenePercent09 { get; set; }
        public string EmpContBeneNm09 { get; set; }
        public string EmpContBeneDob09 { get; set; }
        public string EmpContBeneRel09 { get; set; }
        public string EmpContBeneSsn09 { get; set; }
        public string EmpContBenePercent09 { get; set; }
        public string SpContBeneNm09 { get; set; }
        public string SpContBeneDob09 { get; set; }
        public string SpContBeneRel09 { get; set; }
        public string SpContBeneSsn09 { get; set; }
        public string SpContBenePercent09 { get; set; }
        public string EmpPrimBeneNm10 { get; set; }
        public string EmpPrimBeneDob10 { get; set; }
        public string EmpPrimBeneRel10 { get; set; }
        public string EmpPrimBeneSsn10 { get; set; }
        public string EmpPrimBenePercent10 { get; set; }
        public string SpPrimBeneNm10 { get; set; }
        public string SpPrimBeneDob10 { get; set; }
        public string SpPrimBeneRel10 { get; set; }
        public string SpPrimBeneSsn10 { get; set; }
        public string SpPrimBenePercent10 { get; set; }
        public string EmpContBeneNm10 { get; set; }
        public string EmpContBeneDob10 { get; set; }
        public string EmpContBeneRel10 { get; set; }
        public string EmpContBeneSsn10 { get; set; }
        public string EmpContBenePercent10 { get; set; }
        public string SpContBeneNm10 { get; set; }
        public string SpContBeneDob10 { get; set; }
        public string SpContBeneRel10 { get; set; }
        public string SpContBeneSsn10 { get; set; }
        public string SpContBenePercent10 { get; set; }
        public string SpEmail { get; set; }
        public string SpTreated6Months { get; set; }
        public string SpDisabled6Months { get; set; }
        public string ReplacementReadAloud { get; set; }
        public string ReplacementIsTerminating { get; set; }
        public string ReplacementUsingFunds { get; set; }
        public string EmpRiderAir { get; set; }
        public string EmpRiderWp { get; set; }
        public string EmpRiderQol3 { get; set; }
        public string EmpRiderQol4 { get; set; }
        public string SpRiderAir { get; set; }
        public string SpRiderWp { get; set; }
        public string SpRiderQol3 { get; set; }
        public string SpRiderQol4 { get; set; }
        public string ReplcmntPolcy1Nm { get; set; }
        public string ReplcmntPolcy1Nmbr { get; set; }
        public string ReplcmntPolcy1Insrd { get; set; }
        public string ReplcmntPolcy1RplcdOrFncng { get; set; }
        public string ReplcmntPolcy1Rsn { get; set; }
        public string ReplcmntPolcy2Nm { get; set; }
        public string ReplcmntPolcy2Nmbr { get; set; }
        public string ReplcmntPolcy2Insrd { get; set; }
        public string ReplcmntPolcy2RplcdOrFncng { get; set; }
        public string ReplcmntPolcy2Rsn { get; set; }
        public string ReplcmntPolcy3Nm { get; set; }
        public string ReplcmntPolcy3Nmbr { get; set; }
        public string ReplcmntPolcy3Insrd { get; set; }
        public string ReplcmntPolcy3RplcdOrFncng { get; set; }
        public string ReplcmntPolcy3Rsn { get; set; }
        public string ReplcmntPolcy4Nm { get; set; }
        public string ReplcmntPolcy4Nmbr { get; set; }
        public string ReplcmntPolcy4Insrd { get; set; }
        public string ReplcmntPolcy4RplcdOrFncng { get; set; }
        public string ReplcmntPolcy4Rsn { get; set; }
        public string EmpInitialsTxt { get; set; }
        public string AgentInitialsTxt { get; set; }
        public string ChCovAmnt01 { get; set; }
        public string ChCovAmnt02 { get; set; }
        public string ChCovAmnt03 { get; set; }
        public string ChCovAmnt04 { get; set; }
        public string ChCovAmnt05 { get; set; }
        public string ChCovAmnt06 { get; set; }
        public DateTime CrtdDt { get; set; }
        public string CrtdBy { get; set; }

        public virtual ICollection<EppErrorDtl> EppErrorDtl { get; set; }
    }
}
